import type { BuyerPlatformProfile } from "@/types/buyer-platform";

function templates(domain: string, productLineId: "masterbatch" | "filament", entries: Array<[string, string, string, BuyerPlatformProfile["bestUseCases"][number]]>) {
  return entries.map(([label, product, intent, useCase]) => ({
    productLineId,
    label,
    queryTemplate: `site:${domain} "${product}" "${intent}"`,
    expectedResult: `${label} 的公开搜索结果，需要人工打开验证。`,
    useCase,
  }));
}

export const BUYER_PLATFORMS: BuyerPlatformProfile[] = [
  {
    id: "alibaba",
    name: "Alibaba",
    category: "global_b2b_rfq",
    domain: "alibaba.com",
    marketPresets: ["global", "russia", "ukraine", "belt_and_road", "custom"],
    countries: [],
    languageHints: ["en"],
    productLineFit: { masterbatch: "high", filament: "high" },
    bestUseCases: ["submit_rfq", "find_suppliers", "compare_prices"],
    resultMeaning: "全球供应商/RFQ入口；RFQ 明细可能需要登录，搜索结果不能直接当作有效求购。",
    riskNotes: ["平台可能展示供应商广告而非买家需求", "RFQ 或买家详情可能需要登录查看", "电商或供应商页不能直接保存为求购"],
    requiresManualVerification: true,
    requiresLoginLikely: true,
    searchTemplates: [
      ...templates("alibaba.com", "masterbatch", [
        ["Alibaba 色母 RFQ", "color masterbatch", "RFQ", "submit_rfq"],
        ["Alibaba 色母询价", "color masterbatch", "Request for Quotation", "submit_rfq"],
        ["Alibaba 塑料着色剂 RFQ", "plastic colorant", "Submit RFQ", "submit_rfq"],
        ["Alibaba 色母买家", "color masterbatch", "buyers", "find_buying_leads"],
      ]),
      ...templates("alibaba.com", "filament", [
        ["Alibaba PLA RFQ", "PLA filament", "RFQ", "submit_rfq"],
        ["Alibaba 3D耗材询价", "3D printer filament", "Request for Quotation", "submit_rfq"],
        ["Alibaba PLA 提交RFQ", "PLA filament", "Submit RFQ", "submit_rfq"],
      ]),
    ],
  },
  ...[
    ["tradewheel", "TradeWheel", "tradewheel.com"],
    ["go4worldbusiness", "Go4WorldBusiness", "go4worldbusiness.com"],
    ["exporthub", "ExportHub", "exporthub.com"],
    ["ec21", "EC21", "ec21.com"],
    ["ecplaza", "ECPlaza", "ecplaza.net"],
    ["tradeford", "TradeFord", "tradeford.com"],
    ["globalsources", "GlobalSources", "globalsources.com"],
    ["b2bmap", "B2BMap", "b2bmap.com"],
    ["eworldtrade", "eWorldTrade", "eworldtrade.com"],
  ].map(([id, name, domain]) => ({
    id,
    name,
    category: "global_b2b_rfq" as const,
    domain,
    marketPresets: ["global", "russia", "ukraine", "belt_and_road", "custom"],
    countries: [],
    languageHints: ["en"],
    productLineFit: { masterbatch: "high" as const, filament: "high" as const },
    bestUseCases: ["find_buying_leads" as const, "find_suppliers" as const],
    resultMeaning: "B2B buying leads / RFQ / supplier 页面入口，必须人工核实日期、买家身份和有效期。",
    riskNotes: ["可能是供应商目录或平台入口", "买家详情可能需要登录或付费", "无日期结果不能当作近期求购"],
    requiresManualVerification: true,
    requiresLoginLikely: true,
    searchTemplates: [
      ...templates(domain, "masterbatch", [["色母 buying leads", "color masterbatch", "buying leads", "find_buying_leads"]]),
      ...templates(domain, "filament", [["3D耗材 buying leads", "PLA filament", "buying leads", "find_buying_leads"]]),
    ],
  })),
  {
    id: "amazon-business",
    name: "Amazon Business",
    category: "business_procurement",
    domain: "business.amazon.com",
    marketPresets: ["global", "custom"],
    countries: ["United States"],
    languageHints: ["en"],
    productLineFit: { masterbatch: "low", filament: "high" },
    bestUseCases: ["compare_prices", "market_validation", "find_distributors"],
    resultMeaning: "企业采购/价格/渠道验证入口，不代表买家求购。",
    riskNotes: ["更适合 3D 耗材渠道验证", "不适合直接判断色母求购", "结果通常是商品或卖家页面"],
    requiresManualVerification: true,
    requiresLoginLikely: false,
    searchTemplates: [
      ...templates("business.amazon.com", "filament", [
        ["Amazon Business 3D耗材", "3D printer filament", "bulk", "market_validation"],
        ["Amazon Business PLA", "PLA filament", "3D printer filament", "compare_prices"],
      ]),
      ...templates("business.amazon.com", "masterbatch", [["Amazon Business 色母低优先级验证", "color masterbatch", "plastic", "market_validation"]]),
    ],
  },
  {
    id: "amazon",
    name: "Amazon",
    category: "marketplace_ecommerce",
    domain: "amazon.com",
    marketPresets: ["global", "custom"],
    countries: ["United States"],
    languageHints: ["en"],
    productLineFit: { masterbatch: "not_recommended", filament: "high" },
    bestUseCases: ["compare_prices", "market_validation", "competitor_check"],
    resultMeaning: "价格、竞品和渠道验证，不代表求购信息。",
    riskNotes: ["电商商品页不是 RFQ", "色母不建议用 Amazon 做重点搜索"],
    requiresManualVerification: true,
    requiresLoginLikely: false,
    searchTemplates: [
      ...templates("amazon.com", "filament", [
        ["Amazon PLA 价格验证", "PLA filament", "3D printer filament", "compare_prices"],
        ["Amazon PETG bulk", "PETG filament", "bulk", "market_validation"],
      ]),
      ...templates("amazon.com", "masterbatch", [["Amazon 色母低优先级验证", "color masterbatch", "plastic", "market_validation"]]),
    ],
  },
  ...[
    ["ozon", "Ozon", "ozon.ru", "russia"],
    ["wildberries", "Wildberries", "wildberries.ru", "russia"],
    ["prom-ua", "Prom.ua", "prom.ua", "ukraine"],
  ].map(([id, name, domain, market]) => ({
    id,
    name,
    category: "marketplace_ecommerce" as const,
    domain,
    marketPresets: [market, "belt_and_road", "custom"],
    countries: market === "russia" ? ["Russia"] : ["Ukraine"],
    languageHints: market === "russia" ? ["ru"] : ["uk", "ru"],
    productLineFit: { masterbatch: "low" as const, filament: "medium" as const },
    bestUseCases: ["compare_prices" as const, "find_distributors" as const, "market_validation" as const],
    resultMeaning: "本地电商渠道、价格和经销商验证，不代表买家求购。",
    riskNotes: ["商品页不是求购信息", "适合作为渠道和价格参考", "保存前必须确认是否有真实公司来源"],
    requiresManualVerification: true,
    requiresLoginLikely: false,
    searchTemplates: [
      ...templates(domain, "filament", [
        [`${name} PLA`, "PLA filament", "3D printer filament", "market_validation"],
        [`${name} 3D耗材`, "3D printer filament", "PLA", "find_distributors"],
      ]),
      ...templates(domain, "masterbatch", [[`${name} 色母低优先级验证`, "masterbatch", "plastic", "market_validation"]]),
    ],
  })),
  ...[
    ["b2b-center", "B2B-Center", "b2b-center.ru", "russia"],
    ["zakupki", "Zakupki", "zakupki.gov.ru", "russia"],
    ["roseltorg", "Roseltorg", "roseltorg.ru", "russia"],
    ["fabrikant", "Fabrikant", "fabrikant.ru", "russia"],
    ["prozorro", "Prozorro", "prozorro.gov.ua", "ukraine"],
    ["smarttender", "SmartTender", "smarttender.biz", "ukraine"],
  ].map(([id, name, domain, market]) => ({
    id,
    name,
    category: "tender_procurement" as const,
    domain,
    marketPresets: [market, "belt_and_road", "custom"],
    countries: market === "russia" ? ["Russia"] : ["Ukraine"],
    languageHints: market === "russia" ? ["ru"] : ["uk", "ru"],
    productLineFit: { masterbatch: "medium" as const, filament: "medium" as const },
    bestUseCases: ["find_tenders" as const, "find_buying_leads" as const],
    resultMeaning: "招标/采购公告入口，更接近真实采购，但必须核实截止日期和准入条件。",
    riskNotes: ["可能已经截止", "可能要求本地资质或注册", "完整文件可能需要登录"],
    requiresManualVerification: true,
    requiresLoginLikely: true,
    searchTemplates: [
      ...templates(domain, "masterbatch", [[`${name} 色母招标`, "masterbatch", "2026", "find_tenders"]]),
      ...templates(domain, "filament", [[`${name} PLA招标`, "PLA filament", "2026", "find_tenders"]]),
    ],
  })),
  ...[
    ["tiu", "Tiu", "tiu.ru", "russia"],
    ["avito", "Avito", "avito.ru", "russia"],
    ["allbiz", "Allbiz", "allbiz.com", "russia"],
  ].map(([id, name, domain, market]) => ({
    id,
    name,
    category: "regional_b2b" as const,
    domain,
    marketPresets: [market, "belt_and_road", "custom"],
    countries: ["Russia"],
    languageHints: ["ru"],
    productLineFit: { masterbatch: "medium" as const, filament: "medium" as const },
    bestUseCases: ["find_distributors" as const, "market_validation" as const],
    resultMeaning: "区域 B2B / 分类入口，适合找本地经销商或市场存在性，不直接代表求购。",
    riskNotes: ["可能是卖家广告", "需要人工核实公司与需求", "无日期结果不能视为近期求购"],
    requiresManualVerification: true,
    requiresLoginLikely: false,
    searchTemplates: [
      ...templates(domain, "masterbatch", [[`${name} 色母区域B2B`, "masterbatch", "поставщик", "find_distributors"]]),
      ...templates(domain, "filament", [[`${name} 3D耗材区域B2B`, "PLA filament", "поставщик", "find_distributors"]]),
    ],
  })),
  ...[
    ["reddit", "Reddit", "reddit.com"],
    ["reprap", "RepRap Forum", "reprap.org"],
    ["prusa-forum", "Prusa Forum", "forum.prusa3d.com"],
    ["stackexchange-3d", "3DPrinting StackExchange", "3dprinting.stackexchange.com"],
    ["quora", "Quora", "quora.com"],
  ].map(([id, name, domain]) => ({
    id,
    name,
    category: "forum_community" as const,
    domain,
    marketPresets: ["global", "russia", "ukraine", "belt_and_road", "custom"],
    countries: [],
    languageHints: ["en"],
    productLineFit: { masterbatch: "low" as const, filament: "high" as const },
    bestUseCases: ["ask_for_supplier_recommendation" as const, "market_validation" as const],
    resultMeaning: "社区需求启发或供应商推荐讨论，不等于企业采购。",
    riskNotes: ["买家身份通常不明确", "可能是个人消费或技术讨论", "只适合继续调研"],
    requiresManualVerification: true,
    requiresLoginLikely: false,
    searchTemplates: [
      ...templates(domain, "filament", [
        [`${name} PLA where to buy`, "PLA filament", "where to buy", "ask_for_supplier_recommendation"],
        [`${name} filament bulk`, "filament supplier", "bulk", "ask_for_supplier_recommendation"],
      ]),
      ...templates(domain, "masterbatch", [[`${name} 色母低优先级讨论`, "color masterbatch", "where to buy", "market_validation"]]),
    ],
  })),
];

export function getBuyerPlatformById(id: string) {
  return BUYER_PLATFORMS.find((platform) => platform.id === id);
}
