/* eslint-disable @typescript-eslint/ban-ts-comment */
// SQLite's fluent query builder has a higher-order generic surface; it is contained in this infrastructure adapter.
// @ts-nocheck
import { desc, eq } from "drizzle-orm";
import type { DatabaseConnection } from "../../db/connection";
import { sourceRuns } from "../../db/schema";
import type { Clock, IdGenerator } from "../../domain/entities/common";
import { sanitizeSourceRunInputSummary, stableJsonStringify } from "../../domain/normalization";
import type { SourceRunRepository } from "../../domain/repositories";
import { RepositoryNotFoundError } from "../../domain/repositories";
import { mapSourceRun } from "./mappers";
const page = (limit?: number, offset?: number) => ({ limit: Math.min(Math.max(limit ?? 50, 1), 100), offset: Math.max(offset ?? 0, 0) });
export class SqliteSourceRunRepository implements SourceRunRepository { constructor(private readonly connection: DatabaseConnection, private readonly clock: Clock, private readonly ids: IdGenerator) {} async create(input: Parameters<SourceRunRepository["create"]>[0]) { const now = this.clock.now(); const row = { id: this.ids.next(), adapterId: input.adapterId, sourceType: input.sourceType, status: "running" as const, inputSummaryJson: stableJsonStringify(sanitizeSourceRunInputSummary(input.inputSummary)), startedAt: (input.startedAt ?? now).getTime(), createdAt: now.getTime(), updatedAt: now.getTime() }; this.connection.db.insert(sourceRuns).values(row).run(); return mapSourceRun(this.connection.db.select().from(sourceRuns).where(eq(sourceRuns.id, row.id)).get()!); } async getById(id: string) { const row = this.connection.db.select().from(sourceRuns).where(eq(sourceRuns.id, id)).get(); return row ? mapSourceRun(row) : null; } async list(options = {}) { const p = page(options.limit, options.offset); return this.connection.db.select().from(sourceRuns).orderBy(desc(sourceRuns.createdAt), desc(sourceRuns.id)).limit(p.limit).offset(p.offset).all().map(mapSourceRun); } async finish(id: string, input: Parameters<SourceRunRepository["finish"]>[1]) { const existing = await this.getById(id); if (!existing) throw new RepositoryNotFoundError("Source run not found."); const finishedAt = input.finishedAt ?? this.clock.now(); if (finishedAt < existing.startedAt) throw new Error("finishedAt cannot be before startedAt."); this.connection.db.update(sourceRuns).set({ status: input.status ?? "success", rawCount: input.resultCounts.raw, acceptedCount: input.resultCounts.accepted, duplicateCount: input.resultCounts.duplicate, unresolvedCount: input.resultCounts.unresolved, failedCount: input.resultCounts.failed, finishedAt: finishedAt.getTime(), updatedAt: this.clock.now().getTime() }).where(eq(sourceRuns.id, id)).run(); return (await this.getById(id))!; } async markFailed(id: string, input: Parameters<SourceRunRepository["markFailed"]>[1]) { const existing = await this.getById(id); if (!existing) throw new RepositoryNotFoundError("Source run not found."); const finishedAt = input.finishedAt ?? this.clock.now(); this.connection.db.update(sourceRuns).set({ status: "failed", finishedAt: finishedAt.getTime(), errorMessage: input.errorMessage.replace(/\n[\s\S]*/g, "").slice(0, 2000), updatedAt: this.clock.now().getTime() }).where(eq(sourceRuns.id, id)).run(); return (await this.getById(id))!; } }
