import { sql } from "drizzle-orm";
import { check, index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
import { accounts } from "./accounts";
import { evidence } from "./evidence";
import { sourceRuns } from "./source-runs";

export const legacyMigrationRuns = sqliteTable("legacy_migration_runs", {
  id: text("id").primaryKey(), exportId: text("export_id").notNull(), formatVersion: integer("format_version").notNull(), sourceStorageKey: text("source_storage_key").notNull(), sourceHash: text("source_hash").notNull(), sourceRunId: text("source_run_id").references(() => sourceRuns.id), status: text("status").notNull(), totalCount: integer("total_count").notNull().default(0), validCount: integer("valid_count").notNull().default(0), warningCount: integer("warning_count").notNull().default(0), invalidCount: integer("invalid_count").notNull().default(0), createAccountCount: integer("create_account_count").notNull().default(0), linkAccountCount: integer("link_account_count").notNull().default(0), manualReviewCount: integer("manual_review_count").notNull().default(0), skippedCount: integer("skipped_count").notNull().default(0), importedCount: integer("imported_count").notNull().default(0), failedCount: integer("failed_count").notNull().default(0), reportJson: text("report_json").notNull().default("{}"), errorMessage: text("error_message"), createdAt: integer("created_at").notNull(), updatedAt: integer("updated_at").notNull(), importedAt: integer("imported_at"), rolledBackAt: integer("rolled_back_at"),
}, (t) => [uniqueIndex("legacy_runs_export_id_unique").on(t.exportId), uniqueIndex("legacy_runs_source_hash_unique").on(t.sourceHash), index("legacy_runs_status_idx").on(t.status), check("legacy_runs_status_check", sql`${t.status} in ('preflighted','importing','completed','partial','failed','rolled_back')`), check("legacy_runs_counts_check", sql`${t.totalCount} >= 0 and ${t.validCount} >= 0 and ${t.warningCount} >= 0 and ${t.invalidCount} >= 0 and ${t.createAccountCount} >= 0 and ${t.linkAccountCount} >= 0 and ${t.manualReviewCount} >= 0 and ${t.skippedCount} >= 0 and ${t.importedCount} >= 0 and ${t.failedCount} >= 0`), check("legacy_runs_json_check", sql`json_valid(${t.reportJson})`), check("legacy_runs_times_check", sql`${t.createdAt} >= 0 and ${t.updatedAt} >= 0 and (${t.importedAt} is null or ${t.importedAt} >= 0) and (${t.rolledBackAt} is null or ${t.rolledBackAt} >= 0)`) ]);

export const legacyMigrationItems = sqliteTable("legacy_migration_items", {
  id: text("id").primaryKey(), migrationRunId: text("migration_run_id").notNull().references(() => legacyMigrationRuns.id), itemIndex: integer("item_index").notNull(), legacyLeadId: text("legacy_lead_id"), itemHash: text("item_hash").notNull(), validationStatus: text("validation_status").notNull(), recommendedAction: text("recommended_action").notNull(), selectedAction: text("selected_action"), plannedAccountGroupKey: text("planned_account_group_key"), selectedAccountId: text("selected_account_id").references(() => accounts.id), accountId: text("account_id").references(() => accounts.id), evidenceId: text("evidence_id").references(() => evidence.id), candidateAccountIdsJson: text("candidate_account_ids_json").notNull().default("[]"), accountResult: text("account_result").notNull().default("none"), evidenceResult: text("evidence_result").notNull().default("none"), importStatus: text("import_status").notNull().default("pending"), warningsJson: text("warnings_json").notNull().default("[]"), errorsJson: text("errors_json").notNull().default("[]"), originalPayloadJson: text("original_payload_json").notNull(), createdAt: integer("created_at").notNull(), updatedAt: integer("updated_at").notNull(),
}, (t) => [uniqueIndex("legacy_items_run_index_unique").on(t.migrationRunId, t.itemIndex), index("legacy_items_run_idx").on(t.migrationRunId), index("legacy_items_lead_idx").on(t.legacyLeadId), index("legacy_items_hash_idx").on(t.itemHash), index("legacy_items_validation_idx").on(t.validationStatus), index("legacy_items_recommended_idx").on(t.recommendedAction), index("legacy_items_selected_idx").on(t.selectedAction), index("legacy_items_status_idx").on(t.importStatus), index("legacy_items_account_idx").on(t.accountId), index("legacy_items_evidence_idx").on(t.evidenceId), check("legacy_items_validation_check", sql`${t.validationStatus} in ('valid','warning','invalid')`), check("legacy_items_recommended_check", sql`${t.recommendedAction} in ('create_new','link_existing','manual_review','skip_invalid','duplicate_in_export')`), check("legacy_items_selected_check", sql`${t.selectedAction} is null or ${t.selectedAction} in ('create_new','link_existing','skip')`), check("legacy_items_account_result_check", sql`${t.accountResult} in ('none','created','linked','retained','restored')`), check("legacy_items_evidence_result_check", sql`${t.evidenceResult} in ('none','created','duplicate','restored')`), check("legacy_items_import_status_check", sql`${t.importStatus} in ('pending','ready','needs_review','skipped','imported','failed','rolled_back')`), check("legacy_items_json_check", sql`json_valid(${t.candidateAccountIdsJson}) and json_valid(${t.warningsJson}) and json_valid(${t.errorsJson}) and json_valid(${t.originalPayloadJson})`), check("legacy_items_times_check", sql`${t.itemIndex} >= 0 and ${t.createdAt} >= 0 and ${t.updatedAt} >= 0`) ]);
