import { sql } from "drizzle-orm";
import { check, index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
import { accounts } from "./accounts";
import { evidence } from "./evidence";

const timestamps = { createdAt: integer("created_at").notNull(), updatedAt: integer("updated_at").notNull(), deletedAt: integer("deleted_at") };
export const productLines = sqliteTable("product_lines", { id: text("id").primaryKey(), code: text("code").notNull(), name: text("name").notNull(), enabled: integer("enabled", { mode: "boolean" }).notNull().default(true), rulesJson: text("rules_json").notNull().default("{}"), createdAt: integer("created_at").notNull(), updatedAt: integer("updated_at").notNull() }, (t) => [uniqueIndex("product_lines_code_unique").on(t.code), check("product_lines_rules_json", sql`json_valid(${t.rulesJson})`)]);
export const contacts = sqliteTable("contacts", { id: text("id").primaryKey(), accountId: text("account_id").notNull().references(() => accounts.id), name: text("name"), role: text("role"), email: text("email"), phone: text("phone"), linkedinUrl: text("linkedin_url"), sourceEvidenceId: text("source_evidence_id").references(() => evidence.id), ...timestamps }, (t) => [index("contacts_account_idx").on(t.accountId)]);
export const signals = sqliteTable("signals", { id: text("id").primaryKey(), accountId: text("account_id").notNull().references(() => accounts.id), productLineId: text("product_line_id").notNull().references(() => productLines.id), signalType: text("signal_type").notNull(), strength: text("strength").notNull(), confidence: text("confidence").notNull(), occurredAt: integer("occurred_at"), detectedAt: integer("detected_at").notNull(), expiresAt: integer("expires_at"), status: text("status").notNull().default("active"), evidenceIdsJson: text("evidence_ids_json").notNull(), reasonsJson: text("reasons_json").notNull(), ruleVersion: text("rule_version").notNull(), supersededBySignalId: text("superseded_by_signal_id"), createdAt: integer("created_at").notNull(), updatedAt: integer("updated_at").notNull() }, (t) => [index("signals_account_product_idx").on(t.accountId, t.productLineId), index("signals_status_idx").on(t.status), check("signals_json_check", sql`json_valid(${t.evidenceIdsJson}) and json_valid(${t.reasonsJson})`)]);
export const opportunities = sqliteTable("opportunities", { id: text("id").primaryKey(), accountId: text("account_id").notNull().references(() => accounts.id), productLineId: text("product_line_id").notNull().references(() => productLines.id), lifecycleStatus: text("lifecycle_status").notNull().default("needs_verification"), priority: text("priority").notNull().default("P3"), totalScore: integer("total_score").notNull().default(0), accountFitScore: integer("account_fit_score").notNull().default(0), intentScore: integer("intent_score").notNull().default(0), freshnessScore: integer("freshness_score").notNull().default(0), evidenceQualityScore: integer("evidence_quality_score").notNull().default(0), actionabilityScore: integer("actionability_score").notNull().default(0), penaltiesJson: text("penalties_json").notNull().default("{}"), signalIdsJson: text("signal_ids_json").notNull().default("[]"), evidenceIdsJson: text("evidence_ids_json").notNull().default("[]"), scoreReasonsJson: text("score_reasons_json").notNull().default("[]"), risksJson: text("risks_json").notNull().default("[]"), recommendedNextAction: text("recommended_next_action").notNull(), verificationStatus: text("verification_status").notNull().default("needs_verification"), assignedAt: integer("assigned_at"), lastScoredAt: integer("last_scored_at").notNull(), scoreVersion: text("score_version").notNull(), ...timestamps }, (t) => [index("opportunities_priority_idx").on(t.priority), index("opportunities_account_idx").on(t.accountId), uniqueIndex("opportunities_active_account_product_unique").on(t.accountId, t.productLineId).where(sql`${t.deletedAt} is null and ${t.lifecycleStatus} not in ('won','lost','rejected','expired')`), check("opportunities_json_check", sql`json_valid(${t.penaltiesJson}) and json_valid(${t.signalIdsJson}) and json_valid(${t.evidenceIdsJson}) and json_valid(${t.scoreReasonsJson}) and json_valid(${t.risksJson})`)]);
export const opportunityScoreRevisions = sqliteTable("opportunity_score_revisions", { id: text("id").primaryKey(), opportunityId: text("opportunity_id").notNull().references(() => opportunities.id), scoreVersion: text("score_version").notNull(), totalScore: integer("total_score").notNull(), componentsJson: text("components_json").notNull(), penaltiesJson: text("penalties_json").notNull(), signalIdsJson: text("signal_ids_json").notNull(), evidenceIdsJson: text("evidence_ids_json").notNull(), reasonsJson: text("reasons_json").notNull(), createdAt: integer("created_at").notNull() }, (t) => [index("score_revisions_opportunity_idx").on(t.opportunityId), check("score_revisions_json_check", sql`json_valid(${t.componentsJson}) and json_valid(${t.penaltiesJson}) and json_valid(${t.signalIdsJson}) and json_valid(${t.evidenceIdsJson}) and json_valid(${t.reasonsJson})`)]);
export const activities = sqliteTable("activities", { id: text("id").primaryKey(), accountId: text("account_id").references(() => accounts.id), opportunityId: text("opportunity_id").references(() => opportunities.id), type: text("type").notNull(), title: text("title").notNull(), note: text("note"), actorType: text("actor_type").notNull().default("user"), metadataJson: text("metadata_json").notNull().default("{}"), createdAt: integer("created_at").notNull() }, (t) => [index("activities_account_idx").on(t.accountId), index("activities_opportunity_idx").on(t.opportunityId), check("activities_metadata_json", sql`json_valid(${t.metadataJson})`)]);
export const followUpTasks = sqliteTable("follow_up_tasks", { id: text("id").primaryKey(), accountId: text("account_id").references(() => accounts.id), opportunityId: text("opportunity_id").references(() => opportunities.id), title: text("title").notNull(), dueAt: integer("due_at").notNull(), status: text("status").notNull().default("pending"), channel: text("channel"), note: text("note"), createdAt: integer("created_at").notNull(), updatedAt: integer("updated_at").notNull(), completedAt: integer("completed_at") }, (t) => [index("follow_up_tasks_due_idx").on(t.status, t.dueAt)]);
export const outreachDrafts = sqliteTable("outreach_drafts", { id: text("id").primaryKey(), accountId: text("account_id").notNull().references(() => accounts.id), opportunityId: text("opportunity_id").references(() => opportunities.id), channel: text("channel").notNull(), subject: text("subject"), body: text("body").notNull(), missingInfoJson: text("missing_info_json").notNull().default("[]"), assumptionsJson: text("assumptions_json").notNull().default("[]"), warningsJson: text("warnings_json").notNull().default("[]"), createdAt: integer("created_at").notNull(), updatedAt: integer("updated_at").notNull(), deletedAt: integer("deleted_at") }, (t) => [index("outreach_drafts_account_idx").on(t.accountId), check("outreach_drafts_json_check", sql`json_valid(${t.missingInfoJson}) and json_valid(${t.assumptionsJson}) and json_valid(${t.warningsJson})`)]);
export const appSettings = sqliteTable("app_settings", { key: text("key").primaryKey(), valueJson: text("value_json").notNull(), updatedAt: integer("updated_at").notNull() }, (t) => [check("app_settings_value_json", sql`json_valid(${t.valueJson})`)]);
