import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { LEGACY_LEADS_STORAGE_KEY, sha256, stableExportCore } from "../src/shared/legacy-migration";
import { preflightLegacyMigration } from "../src/server/application/legacy-migration/preflight";
import { importLegacyMigrationRun } from "../src/server/application/legacy-migration/import-run";
import { createDatabaseConnection } from "../src/server/db/connection";
import { migrateDatabase } from "../src/server/db/migrate";
import { createSqliteRepositories } from "../src/server/repositories/sqlite/create-sqlite-repositories";

class Clock { now() { return new Date("2026-07-16T00:00:00.000Z"); } }
class Ids { private count = 0; next() { return `20000000-0000-4000-8000-${String(++this.count).padStart(12, "0")}`; } }
const dir = mkdtempSync(join(tmpdir(), "phase1c-import-")); const database = join(dir, "test.db");
let connection: ReturnType<typeof createDatabaseConnection>; let repos: ReturnType<typeof createSqliteRepositories>;
const dependencies = () => ({ accounts: repos.accounts, evidence: repos.evidence, sourceRuns: repos.sourceRuns, migrations: repos.legacyMigrations, clock: new Clock() });
const backup = (payload: unknown, exportId: string) => { const rawValue = JSON.stringify(payload); const entries = [{ key: LEGACY_LEADS_STORAGE_KEY, rawValue, sha256: sha256(rawValue) }]; const core = { format: "ai-trade-leads-localstorage-backup" as const, formatVersion: 1 as const, exportId, exportedAt: "2026-07-16T00:00:00.000Z", sourceOrigin: "http://localhost", applicationVersion: "v0.6-localstorage" as const, entries }; return { ...core, payloadSha256: sha256(stableExportCore(core)) }; };
test.before(() => { migrateDatabase(database); connection = createDatabaseConnection(database); repos = createSqliteRepositories(connection, { clock: new Clock(), idGenerator: new Ids() }); });
test.after(() => { assert.deepEqual(connection.sqlite.pragma("foreign_key_check"), []); connection.close(); rmSync(dir, { recursive: true, force: true }); });

test("import blocks unresolved manual decisions", async () => { const account = await repos.accounts.create({ displayName: "Existing", websiteUrl: "https://existing.example" }); const run = await preflightLegacyMigration(backup([{ companyName: "Existing", website: "https://existing.example" }], "manual-block"), { legacyMigrationRepository: repos.legacyMigrations, accountRepository: repos.accounts, clock: new Clock() }); assert.equal(run.manualReviewCount, 0); const item = (await repos.legacyMigrations.listItems(run.id))[0]!; await repos.legacyMigrations.updateItemDecision(item.id, { selectedAction: "link_existing", selectedAccountId: account.id, approvedManualAccountSelection: true }); const imported = await importLegacyMigrationRun(run.id, dependencies()); assert.equal(imported.status, "completed"); });
test("import creates account and evidence without inferring contact or country", async () => { const run = await preflightLegacyMigration(backup([{ id: "legacy-1", companyName: "Import Co", sourceUrl: "https://source.example", fetchedAt: "2026-07-01T00:00:00.000Z", email: "kept-only-in-payload" }], "create-import"), { legacyMigrationRepository: repos.legacyMigrations, accountRepository: repos.accounts, clock: new Clock() }); const complete = await importLegacyMigrationRun(run.id, dependencies()); const item = (await repos.legacyMigrations.listItems(run.id))[0]!; assert.equal(complete.status, "completed"); assert.equal(item.importStatus, "imported"); assert.ok(item.accountId); assert.ok(item.evidenceId); assert.equal((await repos.accounts.getById(item.accountId!))?.countryCode, null); assert.equal((await repos.evidence.getById(item.evidenceId!))?.publishedAt, null); });
test("batch grouping reuses account and repeated import is idempotent", async () => { const run = await preflightLegacyMigration(backup([{ companyName: "Group A", website: "https://group.example", sourceUrl: "https://one.example" }, { companyName: "Group B", website: "https://group.example/path", sourceUrl: "https://two.example" }], "group-import"), { legacyMigrationRepository: repos.legacyMigrations, accountRepository: repos.accounts, clock: new Clock() }); await importLegacyMigrationRun(run.id, dependencies()); const first = await repos.legacyMigrations.listItems(run.id); assert.equal(first[0]?.accountId, first[1]?.accountId); const rerun = await importLegacyMigrationRun(run.id, dependencies()); assert.equal(rerun?.status, "completed"); assert.equal((await repos.legacyMigrations.listItems(run.id))[0]?.evidenceId, first[0]?.evidenceId); });
test("duplicate evidence remains traceable", async () => { const first = await preflightLegacyMigration(backup([{ id: "same-source", companyName: "Dup", sourceUrl: "https://dup.example" }], "dup-one"), { legacyMigrationRepository: repos.legacyMigrations, accountRepository: repos.accounts, clock: new Clock() }); await importLegacyMigrationRun(first.id, dependencies()); const second = await preflightLegacyMigration(backup([{ id: "same-source", companyName: "Dup two", sourceUrl: "https://dup.example" }], "dup-two"), { legacyMigrationRepository: repos.legacyMigrations, accountRepository: repos.accounts, clock: new Clock() }); await importLegacyMigrationRun(second.id, dependencies()); assert.equal((await repos.legacyMigrations.listItems(second.id))[0]?.evidenceResult, "duplicate"); });
